version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    links:
      - redis
    environment:
      REDIS_LOCAL_URL: "redis:6379"
    networks:
      - appexample
  redis:
    image: "redis:alpine"
    networks:
      - appexample
    ports:
    - "6379:6379"
  networks:
    appexample: